
-- This file contains all the queries used for the data analysis project. It includes queries to create views,calculate revenue, and analyze booking trends.

-- Main query for power bi
with hotel as (
    SELECT *
    from hotel_2018
         union all
    SELECT *
    from hotel_2019
        union all
    SELECT *
    from hotel_2020
)
SELECT
    hotel.*,
    market_segment.discount as market_discount,
    meal_cost.cost as meal_cost
FROM hotel
    left JOIN market_segment
        on hotel.market_segment = market_segment.market_segment
    left join meal_cost
        on hotel.meal = meal_cost.meal_name;

/*this view will be used to calculate the total revenue generated by each booking,
taking into account the number of nights stayed, the average daily rate (ADR),
any applicable discounts based on the market segment,
and the cost of meals. The revenue is formatted as a string with commas for easier readability.
*/
CREATE view revenue as
select
    hotel.arrival_date_year,
    hotel.arrival_date_month,
    hotel.hotel,
    hotel.market_segment,
    hotel.meal,
    hotel.meal_cost,
    hotel.is_canceled,
    hotel.is_repeated_guest,
    hotel.stays_in_weekend_nights,
    hotel.stays_in_week_nights,
    hotel.customer_type,
    hotel.distribution_channel,
    sum((stays_in_weekend_nights + stays_in_week_nights) *hotel.adr * 
    (1 - market_discount) + (stays_in_weekend_nights + stays_in_week_nights)
     * hotel.meal_cost) as total_revenue
from hotel
    left join market_segment
        on hotel.market_segment = market_segment.market_segment
    left join meal_cost
        on hotel.meal = meal_cost.meal_name
    group by hotel.arrival_date_year, hotel.arrival_date_month, hotel.hotel,
     hotel.market_segment, hotel.meal, hotel.meal_cost, hotel.is_canceled,
      hotel.is_repeated_guest, hotel.stays_in_weekend_nights, hotel.stays_in_week_nights,
       hotel.customer_type, hotel.distribution_channel;

/* This view will be used to analyze the hotel data by combining information from multiple years
(2018, 2019, and 2020)
and enriching it with additional details such as market segment discounts and meal costs.
It allows for a comprehensive analysis of hotel bookings, revenue, and trends over time. */

create view hotel as
 SELECT 
 hotel.*,
market_segment.discount as market_discount,
meal_cost.cost as meal_cost
 from (
    select *
    from hotel_2018
         union all
    SELECT *
    from hotel_2019
        union all
    SELECT *
    from hotel_2020
 ) as hotel
    left JOIN market_segment
        on hotel.market_segment = market_segment.market_segment
    left join meal_cost
        on hotel.meal = meal_cost.meal_name

-- Objectives
-- Revenue
-- Is our revenue growing
select
    arrival_date_year,
    to_char(sum((stays_in_weekend_nights + stays_in_week_nights) *adr * 
    (1 - market_discount) + (stays_in_weekend_nights + stays_in_week_nights) * meal_cost),
    'fm999,999,999') as total_revenue
from hotel
    where is_canceled = 0
    group by arrival_date_year
    ORDER BY arrival_date_year DESC;

-- How much dicount we we offered
SELECT
    to_char(sum((stays_in_week_nights + stays_in_weekend_nights) * adr * market_discount),
    'fm999,999,999') as dicount
from hotel;

-- How much revenue we have by hotel
select
    hotel,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0
    group by hotel;

-- How much discount we offered per hotel
SELECT
    hotel,
    to_char(sum((stays_in_week_nights + stays_in_weekend_nights) * adr * market_discount),
    'fm999,999,999') as dicount
from hotel
    GROUP BY hotel;

-- How much revenue we have by market segment
select
    market_segment,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0
    group by market_segment
    order by market_segment desc;

-- How much discount we offered per market segment
SELECT
    market_segment,
    to_char(sum((stays_in_week_nights + stays_in_weekend_nights) * adr * market_discount), 'fm999,999,999') as dicount
from hotel
    where market_segment <> 'Undefined'
    group by market_segment, market_discount
    order by market_discount desc;

-- How much revenue we have by distribution channel
select
    distribution_channel,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue        
    where is_canceled = 0
    group by distribution_channel
    order by total_revenue desc;

-- How much revenue we have by meal
select
    meal,
    meal_cost,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0 and meal <> 'Undefined'
    group by meal, meal_cost
    order by total_revenue desc;

-- How much revenue we have by year and month
select
    arrival_date_year,
    arrival_date_month,
    to_char(sum(total_revenue),
    'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0
    group by arrival_date_month, arrival_date_year
    order by arrival_date_year, arrival_date_month;

-- How much revenue we have by customer type
select
    customer_type,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0
    group by customer_type
    order by total_revenue desc;

-- How much revenue we have by repeated guest or new guest
select
    case
        when is_repeated_guest = 0 then 'new guest'
        when is_repeated_guest = 1 then 'repeated guest'
    end as guest category,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    where is_canceled = 0
    group by is_repeated_guest
    order by total_revenue desc;

-- How much lose we have from canceled bookings
select
    case
        when is_canceled = 0 then 'non-canceled bookings'
        when is_canceled = 1 then 'canceled bookings'
    end as booking_status,
    to_char(sum(total_revenue), 'fm999,999,999') as total_revenue
from revenue
    group by is_canceled
    order by total_revenue desc;

-- How many parking lots consumed by year
select
    arrival_date_year,
   sum(required_car_parking_spaces) as total_parking_lots
from hotel
    group by arrival_date_year
    order by arrival_date_year desc;

-- How many parking lots consumed by market segment
select
    market_segment,
   sum(required_car_parking_spaces) as total_parking_lots
from hotel
    group by market_segment
    order by total_parking_lots desc;

-- How many parking lots consumed by customer type
select
    customer_type,
   sum(required_car_parking_spaces) as total_parking_lots
from hotel
    group by customer_type
    order by total_parking_lots desc;

-- Noticable difference trends :
-- Requoierd lead time
select
    min(lead_time) as "minimum lead time",
    max(lead_time) as "maximum lead time",
    round(avg(lead_time), 0) as "average lead time"
from hotel;


-- How many canceled bookings we have
select 
    count(is_canceled) as total_canceled_bookings
from hotel
    where is_canceled = 1;

-- How many non-canceled bookings we have
select
    count(is_canceled) as total_non_canceled_bookings
from hotel
    where is_canceled = 0

-- How many bookings we have by season
select 
    count(*) as total_bookings,
    CASE
        WHEN arrival_date_month IN ('December', 'January', 'February') THEN 'Winter'
        WHEN arrival_date_month IN ('March', 'April', 'May') THEN 'Spring'
        WHEN arrival_date_month IN ('June', 'July', 'August') THEN 'Summer'
        WHEN arrival_date_month IN ('September', 'October', 'November') THEN 'Autumn'
    END AS season
from hotel
    where is_canceled = 0
    group by season;

-- How many canceled bookings we have by season
select 
    count(*) as total_bookings,
    CASE
        WHEN arrival_date_month IN ('December', 'January', 'February') THEN 'Winter'
        WHEN arrival_date_month IN ('March', 'April', 'May') THEN 'Spring'
        WHEN arrival_date_month IN ('June', 'July', 'August') THEN 'Summer'
        WHEN arrival_date_month IN ('September', 'October', 'November') THEN 'Autumn'
    END AS season
from hotel
    where is_canceled = 1
    group by season;

-- What is the most booked rooms
select
    Assigned_room_type,
    count(*) as total_booking
from hotel
    where is_canceled = 0
    GROUP BY assigned_room_type
    order by total_booking desc;

-- What is the most canceled rooms
select
    Assigned_room_type,
    count(*) as total_booking
from hotel
    where is_canceled = 1
    GROUP BY assigned_room_type
    order by total_booking desc;

-- How many weekend and week nights we have per hotel
select 
    hotel,
    sum(stays_in_weekend_nights) as total_weekend_nights,
    sum(stays_in_week_nights) as total_week_nights
from hotel
    where is_canceled = 0
    GROUP BY hotel;

-- How many bookings we have by customer type
select
    count(*) as total_bookings,
    customer_type
from hotel
    where is_canceled = 0
    group by customer_type
    order by total_bookings desc;


-- How many bookings we have by guest category (solo, couple, family with kids, group)
select
    case
        when COALESCE(NULLIF(children, 'NA')::numeric, 0) > 0 
        or babies > 0 then 'family with kids'
        when adults = 1 then 'solo guest'
        when adults = 2 then 'couple'
        when adults > 2 then 'group'
        else 'other'
    end as guest_category,
    count(*) as total_bookings
from hotel
    where is_canceled = 0
    group by guest_category;

-- How many bookings we have by market segment
select
    market_segment,
    count(*) as total_bookings
from hotel
    where is_canceled = 0
    group by market_segment
    order by total_bookings desc;

-- How many canceled bookings we have by market segment
select
    market_segment,
     count(*) as total_bookings
from hotel
    where is_canceled = 1
    group by market_segment
    order by total_bookings desc;

-- How many bookings we have by distribution channel
select
    distribution_channel,
     count(*) as total_bookings
from hotel
    where is_canceled = 0
    group by distribution_channel
    order by total_bookings desc;

-- How many canceled bookings we have by distribution channel
select
    distribution_channel,
     count(*) as total_bookings
from hotel
    where is_canceled = 1
    group by distribution_channel
    order by total_bookings desc;

-- Is repeated guest or new guest more frequent
select
    case
        when is_repeated_guest = 0 then 'new guest'
        when is_repeated_guest = 1 then 'repeated guest'
    end as guest_category,
    count(*) as total_bookings
from hotel
    where is_canceled = 0
    group by is_repeated_guest
    order by total_bookings desc;

-- How many canceled bookings we have by repeated guest or new guest
select
    case
        when is_repeated_guest = 0 then 'new guest'
        when is_repeated_guest = 1 then 'repeated guest'
    end as guest_category,
    count(*) as total_bookings
from hotel
    where is_canceled = 1
    group by is_repeated_guest
    order by total_bookings desc;
